name: Sync Upstream

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/eryajf/Thanks-Mirror # change this
          upstream_branch: main # change this
          downstream_branch: main # change this
          token: ${{ secrets.GITHUB_TOKEN }}
